services:

  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - "5423:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_URL=postgres://user:password@db:5432/

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  app1:
    container_name: app1
    environment:
      SERVER_ID: SERVER-1
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
  
  app2:
    container_name: app2
    environment:
      SERVER_ID: SERVER-2
    build: .
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    
    celery:
      container_name: celery
      build: .
      command: celery -A src worker -l info
      volumes:
        - .:/app
      depends_on:
        - redis
        - db
