name: CI Pipeline

on:
  push:
    branches:
      - main
      - cicd
  pull_request:
    branches:
      - main
      - cicd

jobs:
  # Job to run tests
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 for Node.js 20

    - name: Set up Python 3.12
      uses: actions/setup-python@v4  # This version will automatically use Node.js 20
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Run tests
      run: pytest src/tests/

  # Job to run flake8
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 for Node.js 20

    - name: Set up Python 3.12
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: 3.12

    - name: Install dependencies for linting
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Flake8
      run: flake8 src/ --max-line-length=88
